
# cargo-vet audits file

[[audits.windows-sys]]
who = "Linus FÃ¤rnstrand <linus@mullvad.net>"
criteria = "safe-to-deploy"
version = "0.48.0"
notes = "This is just a test audit to explore cargo-vet. DO NOT TRUST THIS AUDIT"
